---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/kustomization-kustomize-v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: renovate-operator
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: renovate-operator
  targetNamespace: renovate
  path: "./kubernetes/apps/renovate/renovate-operator/app"
  interval: 1h
  timeout: 5m
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-ops-kubernetes
    namespace: flux-system
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2
      kind: HelmRelease
      name: renovate-operator
      namespace: renovate
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/kustomization-kustomize-v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: renovate-operator-jobs
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: renovate-operator
  targetNamespace: renovate
  path: "./kubernetes/apps/renovate/renovate-operator/jobs"
  interval: 1h
  timeout: 5m
  prune: true
  wait: false
  sourceRef:
    kind: GitRepository
    name: home-ops-kubernetes
    namespace: flux-system
  dependsOn:
    - name: renovate-operator
