---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - https://raw.githubusercontent.com/Kuadrant/mcp-gateway/refs/heads/main/charts/mcp-gateway/crds/mcp.kuadrant.io_mcpgatewayextensions.yaml
  - https://raw.githubusercontent.com/Kuadrant/mcp-gateway/refs/heads/main/charts/mcp-gateway/crds/mcp.kuadrant.io_mcpserverregistrations.yaml
  - https://raw.githubusercontent.com/Kuadrant/mcp-gateway/refs/heads/main/charts/mcp-gateway/crds/mcp.kuadrant.io_mcpvirtualservers.yaml
