---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1
kind: Component
resources:
  - ./allow-apiserver.yaml
  - ./allow-dns.yaml
  - ./allow-host-probes.yaml
  - ./allow-intra-namespace.yaml
  - ./allow-monitoring-scrape.yaml
