---
# yaml-language-server: $schema=https://k8s-schemas.bjw-s.dev/gateway.networking.k8s.io/gateway_v1.json
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: mcp-gateway
  annotations:
    external-dns.alpha.kubernetes.io/target: &hostname mcp-gateway.mcp.${SECRET_DOMAIN}
spec:
  gatewayClassName: istio
  infrastructure:
    annotations:
      external-dns.alpha.kubernetes.io/hostname: *hostname
      lbipam.cilium.io/ips: "${SVC_MCPGATEWAY_ADDR}"
      #istio: ingressgateway
      gateway.io/name: mcp-gateway
      sidecar.istio.io/inject: "true"
  listeners:
    - name: mcp # gateway listener
      hostname: "mcp-gateway.mcp.thesteamedcrab.com" #public accessibly MCP host one used by client
      protocol: HTTP
      port: 8080
      allowedRoutes:
        namespaces:
          from: All # TODO? Same like internal/external?
    - name: mcps
      port: 8080
      protocol: HTTP
      hostname: "*.mcp.local" # this hostname can be any wildcard. It is here to simplify routing, ensure the MCP Server routes attach to this listener only, can be protected by the AuthPolicy and routed to via envoy and the MCPRouter.
      allowedRoutes:
        namespaces:
          from: All #any namespace can register an MCP server route
      #tls:
      #  certificateRefs:
      #    - kind: Secret
      #      name: "${SECRET_DOMAIN/./-}-tls"
