---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./cnp-allow.yaml
  - ./externalsecret.yaml
  - ./gateway.yaml
  - ./helmrelease.yaml
  - ./httproute-broker.yaml
  - ./httproute.yaml
  - ./mcpgatewayextension.yaml
  - ./ocirepository.yaml
  - ./podmonitor.yaml
  - ./rotator-cronjob.yaml
  - ./rotator-rbac.yaml
  - ./securitypolicy.yaml
