---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: dragonfly-operator
spec:
  chartRef:
    kind: OCIRepository
    name: dragonfly-operator
  interval: 1h
  values:
    grafanaDashboard:
      enabled: true
      annotations:
        name: grafana_folder
      folder: Storage
    serviceMonitor:
      enabled: false
