---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/kustomization-kustomize-v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &appname scanservjs
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: *appname
  targetNamespace: collab
  path: "./kubernetes/apps/collab/scanservjs/app"
  interval: 30m
  wait: false
  dependsOn:
    - name: onepassword-connect
      namespace: external-secrets
