---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: frigate
spec:
  chartRef:
    kind: OCIRepository
    name: app-template

  interval: 30m
  values:
    controllers:
      main:
        pod:
          annotations:
            k8s.v1.cni.cncf.io/networks: frigate-security-static

          nodeSelector:
            google.feature.node.kubernetes.io/coral-usb: "true"
            intel.feature.node.kubernetes.io/gpu: "true"
            node.network/vlan-security: "true"

          priorityClassName: home-cluster-critical

        annotations:
          reloader.stakater.com/auto: "true"

        type: statefulset

        containers:
          main:
            image:
              repository: ghcr.io/blakeblackshear/frigate
              tag: 0.17.1@sha256:1724960349dad0bd2ae8ec884171a6fd5755a4dc242a0e66cadbda9c0e85c99b

            env:
              # LIBVA_DRIVER_NAME: i965
              LIBVA_DRIVER_NAME: iHD
              # surpress error message documented here: https://github.com/blakeblackshear/frigate/discussions/15362
              OPENCV_LOG_LEVEL: FATAL

            envFrom:
              - secretRef:
                  name: frigate

            probes:
              liveness:
                enabled: false
                custom: true
                spec:
                  failureThreshold: 30
                  httpGet:
                    path: /api/version
                    port: &unsecurePort 5000
                  initialDelaySeconds: 0
                  periodSeconds: 10
                  timeoutSeconds: 7
              readiness:
                enabled: false
                custom: true
                spec:
                  failureThreshold: 30
                  httpGet:
                    path: /api/version
                    port: *unsecurePort
                  initialDelaySeconds: 0
                  periodSeconds: 10
                  timeoutSeconds: 7
              startup:
                enabled: false
                custom: true
                spec:
                  failureThreshold: 30

                  httpGet:
                    path: /api/version
                    port: *unsecurePort
                  periodSeconds: 10
                  timeoutSeconds: 1
            resources:
              requests:
                cpu: 3
                gpu.intel.com/i915: "1"
                memory: 14Gi
              limits:
                gpu.intel.com/i915: "1"
                memory: 14Gi

            securityContext:
              capabilities:
                drop: ["ALL"]
              privileged: true

    service:
      main:
        controller: main
        ports:
          go2rtc-tcp:
            enabled: true
            port: 1984
            primary: false
            protocol: TCP
            targetPort: 1984
          go2rtc-udp:
            enabled: true
            port: 1984
            primary: false
            protocol: UDP
            targetPort: 1984
          http:
            port: &securePort 8971
          rtsp:
            port: 8554
          unsecure:
            port: *unsecurePort


    route:
      main:
        annotations:
          glance/icon: "https://cdn.jsdelivr.net/gh/homarr-labs/dashboard-icons/png/frigate.png"
          glance/id: "Security"
          glance/name: "Frigate"
          glance/show: "true"
          startpunkt.ullberg.us/enable: "true"
          startpunkt.ullberg.us/group: "security"
          startpunkt.ullberg.us/icon: mdi:cctv
          startpunkt.ullberg.us/instance: "user"
          startpunkt.ullberg.us/name: "Security Cameras"
        hostnames:
          - "{{ .Release.Name }}.${SECRET_DOMAIN}"
        parentRefs:
          - name: internal
            namespace: network
            sectionName: https
        rules:
          - backendRefs:
              - identifier: main
                port: *securePort
    persistence:
      cache:
        type: emptyDir
        medium: Memory
        sizeLimit: 2Gi
        globalMounts:
          - path: /dev/shm

      clips:
        existingClaim: frigate-clips-pvc
        globalMounts:
          - path: /media/frigate/clips

      config:
        enabled: true
        existingClaim: frigate-config-pvc
        globalMounts:
          - path: /config

      exports:
        existingClaim: frigate-exports-pvc
        globalMounts:
          - path: /media/frigate/exports

      recordings:
        existingClaim: frigate-recordings-pvc
        globalMounts:
          - path: /media/frigate/recordings

      usb:
        type: hostPath
        hostPath: /dev/bus/usb
        hostPathType: Directory
        advancedMounts:
          main:
            main:
              - path: /dev/bus/usb
