---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
components:
  - ../../../../components/repos/app-template
resources:
  - ./cnp-allow.yaml
  - ./externalsecret.yaml
  - ./helmrelease.yaml
  - ./longhorn-pvc.yaml
  - ./nfs-pvc.yaml
  - ./prometheusrule.yaml
  - ./restart-cronjob.yaml
  - ./restart-rbac.yaml
  - ./snapshot-cnp.yaml
  - ./snapshot-cronjob.yaml
  - ./snapshot-externalsecret.yaml
  - ./snapshot-rbac.yaml
  - ./snapshot-script-cm.yaml
  - ./securitypolicy.yaml
