---
# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/master-standalone-strict/persistentvolume-v1.json
apiVersion: v1
kind: PersistentVolume
metadata:
  name: frigate-recordings-pv
  labels:
    type: nfs
spec:
  storageClassName: frigate-recordings-storage-class
  capacity:
    storage: 5300G
  accessModes:
    - ReadWriteOnce
  nfs:
    server: "${NFS_HOST_SECURITY}"
    path: /mnt/frigate-media/frigate/recordings

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: frigate-recordings-pvc
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 5300G
  volumeName: frigate-recordings-pv
  storageClassName: frigate-recordings-storage-class

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: frigate-clips-pv
  labels:
    type: nfs
spec:
  storageClassName: frigate-clips-storage-class
  capacity:
    storage: 700G
  accessModes:
    - ReadWriteOnce
  nfs:
    server: "${NFS_HOST_SECURITY}"
    path: /mnt/frigate-media/frigate/clips

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: frigate-clips-pvc
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 700G
  volumeName: frigate-clips-pv
  storageClassName: frigate-clips-storage-class

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: frigate-exports-pv
  labels:
    type: nfs
spec:
  storageClassName: frigate-exports-storage-class
  capacity:
    storage: 10G
  accessModes:
    - ReadWriteOnce
  nfs:
    server: "${NFS_HOST_2}"
    path: /mnt/mass_storage/kubernetes/frigate-exports

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: frigate-exports-pvc
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 10G
  volumeName: frigate-exports-pv
  storageClassName: frigate-exports-storage-class
