---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: swiparr
spec:
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: app-template

  values:
    controllers:
      main:
        type: statefulset

        annotations:
          reloader.stakater.com/auto: "true"

        containers:
          main:
            image:
              repository: ghcr.io/m3sserstudi0s/swiparr
              tag: 1.3.5@sha256:f938ffacbc9c648727ea587a8871790d483c9ed8f2e312b48b7fa602b12b3643
            env:
              JELLYFIN_URL: "http://jellyfin.media:8096"
              JELLYFIN_USE_WATCHLIST: false
              USE_SECURE_COOKIES: true

            resources:
              requests:
                cpu: 15m
                memory: 300Mi
              limits:
                memory: 300Mi

            probes:
              liveness: &probes
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /api/health
                    port: &httpPort 4321
                  initialDelaySeconds: 10
                  periodSeconds: 30
                  timeoutSeconds: 5
                  failureThreshold: 3
              readiness: *probes
              startup: *probes

    service:
      main:
        controller: main
        ports:
          http:
            port: *httpPort

    route:
      main:
        hostnames:
          - "{{ .Release.Name }}.${SECRET_DOMAIN}"
        parentRefs:
          - name: internal
            namespace: network
            sectionName: https
        rules:
          - backendRefs:
              - identifier: main
                port: *httpPort
        annotations:
          glance/name: "Swiparr"
          glance/show: "true"
          glance/icon: "https://cdn.jsdelivr.net/gh/homarr-labs/dashboard-icons/png/swiparr.png"
          glance/id: "Collaboration"

    persistence:
      data:
        existingClaim: swiparr-data-pvc
        globalMounts:
          - path: /app/data
