---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kube-prometheus-stack
spec:
  chartRef:
    kind: OCIRepository
    name: kube-prometheus-stack
  interval: 1h
  dependsOn:
    - name: rook-ceph-cluster
      namespace: rook-ceph

  values:
    alertmanager:
      alertmanagerSpec:
        alertmanagerConfiguration:
          global:
            resolveTimeout: 5m
          name: alertmanager
        externalUrl: https://alertmanager.${SECRET_DOMAIN}
        storage:
          volumeClaimTemplate:
            spec:
              resources:
                requests:
                  storage: 1Gi

              storageClassName: ceph-block
      route:
        main:
          annotations:
            glance/icon: "https://cdn.jsdelivr.net/gh/homarr-labs/dashboard-icons/png/alertmanager.png"
            glance/id: "Observability"

            glance/name: "Alert Manager"
            glance/show: "true"
          enabled: true
          hostnames:
            - alertmanager.${SECRET_DOMAIN}
          parentRefs:
            - name: internal
              namespace: network
              sectionName: https
    cleanPrometheusOperatorObjectNames: true

    ###
    ### Component values
    ###
    crds:
      enabled: false
    grafana:
      enabled: false
      forceDeployDashboards: true
      sidecar:
        dashboards:
          annotations:
            grafana_folder: Kubernetes

    ###
    ### Prometheus operator values
    ###
    kubeApiServer:
      enabled: true
      endpoints: ["192.168.1.9", "192.168.4.9", "192.168.4.10"]
      serviceMonitor:
        metricRelabelings:
          # Drop high cardinality labels
          - action: drop
            regex: (apiserver|etcd|rest_client)_request(|_sli|_slo)_duration_seconds_bucket
            sourceLabels: ["__name__"]
          - action: drop
            regex: (apiserver_response_sizes_bucket|apiserver_watch_events_sizes_bucket|apiserver_request_total)
            sourceLabels: ["__name__"]
          - action: drop
            regex: code_verb:apiserver_request_total:increase1h[30d]
            sourceLabels: ["__name__"]
          - action: drop
            regex: ".*apiserver_request_total.*"

            sourceLabels: ["__name__"]
    kubeControllerManager:
      enabled: true
      endpoints: ["192.168.1.9", "192.168.4.9", "192.168.4.10"]

    kubeEtcd:
      enabled: true
      endpoints: ["192.168.1.9", "192.168.4.9", "192.168.4.10"]
    kubeProxy:
      enabled: false

    kubeScheduler:
      enabled: true
      endpoints: ["192.168.1.9", "192.168.4.9", "192.168.4.10"]

    kubeStateMetrics:
      enabled: false


    kubelet:
      enabled: true
      serviceMonitor:
        metricRelabelings:
          # Drop high cardinality labels
          - action: labeldrop
            regex: (uid)
          - action: labeldrop
            regex: (id|name)
          - action: drop
            regex: (rest_client_request_duration_seconds_bucket|rest_client_request_duration_seconds_sum|rest_client_request_duration_seconds_count)

            sourceLabels: ["__name__"]
    nodeExporter:
      enabled: false

    prometheus:
      prometheusSpec:
        enableRemoteWriteReceiver: true
        externalUrl: https://prometheus.${SECRET_DOMAIN}
        image:
          registry: docker.io
          repository: prompp/prompp
          tag: 2.53.2-0.3.3
        podMonitorSelectorNilUsesHelmValues: false
        probeSelectorNilUsesHelmValues: false
        resources:
          limits:
            memory: 3G
          requests:
            cpu: 100m
            memory: 3G
        retention: 14d
        retentionSize: 100GB
        ruleSelectorNilUsesHelmValues: false
        scrapeConfigSelectorNilUsesHelmValues: false
        scrapeInterval: 1m # Must match interval in Grafana Helm chart
        securityContext:
          fsGroup: 64535
          runAsGroup: 64535
          runAsNonRoot: true
          runAsUser: 64535
        serviceMonitorSelectorNilUsesHelmValues: false
        storageSpec:
          volumeClaimTemplate:
            spec:
              resources:
                requests:
                  storage: 110Gi
              storageClassName: ceph-block
      route:
        main:
          annotations:
            glance/icon: "https://cdn.jsdelivr.net/gh/homarr-labs/dashboard-icons/png/prometheus.png"
            glance/id: "Observability"
            glance/name: "Prometheus"
            glance/show: "true"
          enabled: true
          hostnames:
            - "prometheus.${SECRET_DOMAIN}"
          parentRefs:
            - name: internal
              namespace: network
              sectionName: https

    prometheusOperator:
      prometheusConfigReloader:
        # resource config for prometheusConfigReloader
        resources:
          limits:
            memory: 32M
          ###
          ### Prometheus instance values
          ###
          requests:
            cpu: 5m
            memory: 32M
      resources:
        limits:
          memory: 326M

        requests:
          cpu: 35m
          memory: 273M
