[settings]
pipx.uvx = true

[env]
MINIJINJA_CONFIG_FILE = "{{config_root}}/.minijinja.toml"

[tools]
"aqua:astral-sh/uv" = "latest"
"aqua:google/yamlfmt" = "latest"
"aqua:rhysd/actionlint" = "latest"
"pipx:flux-local" = "latest"
