---
ignore: |
  *.sops.*
  **/resources/

extends: default

rules:
  braces:
    max-spaces-inside: 1
    min-spaces-inside: 0
  brackets:
    max-spaces-inside: 1
    min-spaces-inside: 0
  comments:
    require-starting-space: true
    min-spaces-from-content: 1
  indentation:
    spaces: consistent
    indent-sequences: consistent
    check-multi-line-strings: false
  line-length: disable
  quoted-strings:
    quote-type: double
    required: false
    allow-quoted-quotes: true
  truthy:
    allowed-values:
      - "true"
      - "false"
      - "on"
