---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app home-assistant
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: app-template

  values:
    controllers:
      main:
        type: statefulset

        annotations:
          reloader.stakater.com/auto: "true"

        initContainers:
          init-db:
            image:
              repository: ghcr.io/home-operations/postgres-init
              tag: 18.3.0@sha256:6fa1f331cddd2eb0b6afa7b8d3685c864127a81ab01c3d9400bc3ff5263a51cf

            envFrom: &envFrom
              - secretRef:
                  name: *app

        containers:
          main:
            image:
              repository: ghcr.io/home-operations/home-assistant
              tag: 2026.4.1@sha256:1000851ce4d5bf2f6790bfc8b9052daa2c33a84f92e0bad7d60e0a9333ff4dc2

            env:
              POSTGRES_HOST: postgres-home-assistant-rw.databases.svc.cluster.local
              POSTGRES_DB: home_assistant

            envFrom: *envFrom

            probes:
              liveness:
                enabled: false
              readiness:
                enabled: false
              startup:
                enabled: false

            resources:
              requests:
                cpu: 100m
                memory: 1.2G
              limits:
                memory: 1.2G
        pod:
          priorityClassName: home-cluster-critical

          securityContext:
            runAsUser: 568
            runAsGroup: 568
            fsGroup: 568
            fsGroupChangePolicy: OnRootMismatch
            supplementalGroups:
              - 100
              - 1010

          annotations:
            k8s.v1.cni.cncf.io/networks: hass-iot-static, hass-security-static

          # IOT VLAN (20), SECURITY VLAN (40)
          affinity:
            nodeAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
                nodeSelectorTerms:
                  - matchExpressions:
                      - key: node.network/vlan-iot
                        operator: In
                        values:
                          - "true"
                      - key: node.network/vlan-security
                        operator: In
                        values:
                          - "true"

    service:
      main:
        controller: main
        type: LoadBalancer
        annotations:
          lbipam.cilium.io/ips: ${SVC_HOME_ASSISTANT_ADDR}
        externalTrafficPolicy: Cluster
        ports:
          http:
            port: &httpPort 8123

    route:
      main:
        hostnames:
          - "hass.${SECRET_DOMAIN}"
        parentRefs:
          - name: external
            namespace: network
            sectionName: https
        rules:
          - backendRefs:
              - identifier: main
                port: *httpPort
        annotations:
          glance/name: "Home Assistant"
          glance/show: "true"
          glance/icon: "https://cdn.jsdelivr.net/gh/homarr-labs/dashboard-icons/png/home-assistant.png"
          glance/id: "Home Automation"
          startpunkt.ullberg.us/enable: "true"
          startpunkt.ullberg.us/icon: "home-automation"
          startpunkt.ullberg.us/group: "home automation"
          startpunkt.ullberg.us/name: "Home Assistant"
          startpunkt.ullberg.us/instance: "user"

    persistence:
      config:
        existingClaim: home-assistant-config-pvc
        globalMounts:
          - path: /config

      media:
        existingClaim: home-assistant-media-pvc
        globalMounts:
          - path: /media

      config-cache:
        accessMode: ReadWriteOnce
        size: 1Gi
        storageClass: ceph-block
        advancedMounts:
          main:
            main:
              - path: /config/.venv

      tmp:
        type: emptyDir
