---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: collab
components:
  - ../../components/alerts
resources:
  - ./namespace.yaml
  - ./atuin/ks.yaml
  - ./exercisediary/ks.yaml
  # - ./nextcloud/ks.yaml
  - ./glance/ks.yaml
  - ./it-tools/ks.yaml
  - ./mealie/ks.yaml
  - ./medikeep/ks.yaml
  - ./nametag/ks.yaml
  - ./obsidian-couchdb/ks.yaml
  - ./open-webui/ks.yaml
  - ./paperless/ks.yaml
  - ./searxng/ks.yaml
  - ./sparkyfitness/ks.yaml
  - ./startpunkt-crds/ks.yaml
  - ./startpunkt-user/ks.yaml
  - ./swiparr/ks.yaml
  - ./workoutdiary/ks.yaml
