---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/monitoring.coreos.com/servicemonitor_v1.json
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: istiod
  labels:
    app.kubernetes.io/component: metrics
    app.kubernetes.io/instance: istiod
    app.kubernetes.io/name: istiod
    prometheus: kube-prometheus
spec:
  endpoints:
    - interval: 30s
      path: /metrics
      port: http-monitoring
      scheme: http
      scrapeTimeout: 10s
  namespaceSelector:
    matchNames:
      - istio-system
  selector:
    matchLabels:
      app: istiod
      istio: pilot
