---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: netdata
spec:
  chart:
    spec:
      # renovate: registryUrl=https://netdata.github.io/helmchart/
      chart: netdata
      sourceRef:
        kind: HelmRepository
        name: netdata

      version: 3.7.173
  interval: 30m
  values:
    child:
      enabled: false

    image:
      repository: ghcr.io/netdata/netdata
      tag: "v2.11.0@sha256:7f77be24746e853158b1bf279c962bf7907975df1b6cc1de138f0726439fc0ef"

    ingress:
      enabled: false

    k8sState:
      enabled: false
    parent:
      alarms:
        storageclass: "ceph-block"
      database:
        storageclass: "ceph-block"

      enabled: true
      resources:
        requests:
          cpu: 25m
          memory: 256Mi
        limits:
          memory: 512Mi
  releaseName: netdata
