---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: netdata
spec:
  chart:
    spec:
      # renovate: registryUrl=https://netdata.github.io/helmchart/
      chart: netdata
      sourceRef:
        kind: HelmRepository
        name: netdata

      version: 3.7.165
  interval: 30m
  values:
    child:
      enabled: false

    image:
      repository: ghcr.io/netdata/netdata
      tag: "v2.10.3"

    ingress:
      enabled: false

    k8sState:
      enabled: false
    parent:
      alarms:
        storageclass: "ceph-block"
      database:
        storageclass: "ceph-block"

      enabled: true
  releaseName: netdata
