---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: descheduler
spec:
  chartRef:
    kind: OCIRepository
    name: descheduler
  interval: 1h
  values:
    deschedulerPolicy:
      metricsProviders:
        - source: KubernetesMetrics
      profiles:
        - name: Default
          pluginConfig:
            - args:
                podProtections:
                  defaultDisabled:
                    - FailedBarePods
                    - PodsWithLocalStorage
              name: DefaultEvictor
            - args:
                metricsUtilization:
                  source: KubernetesMetrics
                thresholds:
                  cpu: 20
                  memory: 20
                  pods: 20
                targetThresholds:
                  cpu: 50
                  memory: 50
                  pods: 50
              name: LowNodeUtilization
            - args:
                excludeOwnerKinds:
                  - Job
                includingInitContainers: true
                minPodLifetimeSeconds: 1800
                reasons:
                  - ContainerStatusUnknown
                  - NodeAffinity
                  - NodeShutdown
                  - Terminated
                  - UnexpectedAdmissionError
              name: RemoveFailedPods
            - name: RemovePodsViolatingInterPodAntiAffinity
            - args:
                nodeAffinityType:
                  - requiredDuringSchedulingIgnoredDuringExecution
              name: RemovePodsViolatingNodeAffinity
            - name: RemovePodsViolatingNodeTaints
            - name: RemovePodsViolatingTopologySpreadConstraint
          plugins:
            balance:
              enabled:
                - LowNodeUtilization
                - RemovePodsViolatingTopologySpreadConstraint
            deschedule:
              enabled:
                - RemoveFailedPods
                - RemovePodsViolatingInterPodAntiAffinity
                - RemovePodsViolatingNodeAffinity
                - RemovePodsViolatingNodeTaints
    deschedulerPolicyAPIVersion: descheduler/v1alpha2
    #tolerations:
    #  - key: node-role.kubernetes.io/control-plane
    #    operator: Equal
    #    value: NoSchedule
    #    effect: NoSchedule
    kind: Deployment
    leaderElection:
      enabled: true
    priorityClassName: system-cluster-critical
    service:
      enabled: true
    serviceMonitor:
      enabled: true
