---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: av1corrector
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: av1corrector-secret
    template:
      data:
        # S3
        AWS_ACCESS_KEY_ID: "{{ .GARAGE_AWS_ACCESS_KEY_ID }}"
        AWS_SECRET_ACCESS_KEY: "{{ .GARAGE_AWS_SECRET_ACCESS_KEY }}"
  dataFrom:
    - extract:
        key: av1corrector
