---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/kustomization-kustomize-v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app av1corrector-secrets
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  targetNamespace: media
  path: ./kubernetes/apps/media/av1corrector/secrets
  interval: 30m
  timeout: 5m
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: home-ops-kubernetes
    namespace: flux-system
  dependsOn:
    - name: authelia
      namespace: auth
    - name: onepassword-connect
      namespace: external-secrets
  healthCheckExprs:
    - apiVersion: external-secrets.io/v1
      kind: ExternalSecret
      current: status.conditions.exists(c, c.type == 'Ready' && c.status == 'True')
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/kustomization-kustomize-v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app av1corrector
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  targetNamespace: media
  path: ./kubernetes/apps/media/av1corrector/app
  interval: 30m
  timeout: 5m
  prune: true
  wait: false
  sourceRef:
    kind: GitRepository
    name: home-ops-kubernetes
    namespace: flux-system
  dependsOn:
    - name: av1corrector
      namespace: databases
    - name: av1corrector-secrets
      namespace: media
  postBuild:
    substituteFrom:
      - kind: Secret
        name: av1corrector-secret
