---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/refs/heads/main/cert-manager.io/certificate_v1.json
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: thesteamedcrab.com
spec:
  secretName: thesteamedcrab-com-tls
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: thesteamedcrab.com
  dnsNames:
    - thesteamedcrab.com
    - "*.app.thesteamedcrab.com"
    - "*.mcp.thesteamedcrab.com"
    - "*.thesteamedcrab.com"
  secretTemplate:
    annotations:
      reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
      reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: "network,istio-system,mcp-system"
      reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
