---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: janitorr
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: janitorr
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        CLIENTS_SONARR_APIKEY: "{{ .SONARR__API_KEY }}"
        CLIENTS_RADARR_APIKEY: "{{ .RADARR__API_KEY }}"
        CLIENTS_JELLYFIN_APIKEY: "{{ .JELLYFIN__API_KEY }}"
        CLIENTS_JELLYFIN_USERNAME: "{{ .JELLYFIN__USERNAME }}"
        CLIENTS_JELLYFIN_PASSWORD: "{{ .JELLYFIN__PASSWORD }}"
        CLIENTS_JELLYSEERR_APIKEY: "{{ .SEERR__API_KEY }}"
  dataFrom:
    - extract:
        key: sonarr
        property: SONARR__API_KEY
    - extract:
        key: radarr
        property: RADARR__API_KEY
    - extract:
        key: jellyfin
        property: JELLYFIN__API_KEY
    - extract:
        key: jellyfin
        property: JELLYFIN__USERNAME
    - extract:
        key: jellyfin
        property: JELLYFIN__PASSWORD
    - extract:
        key: seerr
        property: SEERR__API_KEY
