---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./barcode-device.yaml
  - ./coral-device.yaml
  - ./intel-gpu.yaml
  - ./nvidia-gpu.yaml
  - ./skyconnect-device.yaml
  - ./vlan-device.yaml
  - ./zigbee-device.yaml
  - ./zwave-device.yaml
