logging:
  level:
    com.github.schaka: INFO
  file:
    name: "/logs/janitorr.log"

file-system:
  access: true
  validate-seeding: false
  leaving-soon-dir: "/leaving-soon"
  media-server-leaving-soon-dir: "/leaving-soon"
  from-scratch: true
  free-space-check-dir: "/data"

application:
  dry-run: true
  run-once: false
  whole-tv-show: false
  whole-show-seeding-check: false
  leaving-soon: 14d
  leaving-soon-threshold-offset-percent: 5
  exclusion-tags:
    - "janitorr-keep"

  media-deletion:
    enabled: true
    movie-expiration:
      20: 365d
    season-expiration:
      20: 365d

  tag-based-deletion:
    enabled: false

  episode-deletion:
    enabled: false

clients:
  default:
    connect-timeout: 60s
    read-timeout: 60s
    level: NONE

  sonarr:
    enabled: true
    url: "http://sonarr.media.svc.cluster.local:8989"
    delete-empty-shows: true
    determine-age-by: MOST_RECENT
    import-exclusions: false

  radarr:
    enabled: true
    url: "http://radarr.media.svc.cluster.local:7878"
    only-delete-files: false
    determine-age-by: MOST_RECENT
    import-exclusions: false

  jellyfin:
    enabled: true
    url: "http://jellyfin.media.svc.cluster.local:8096"
    delete: true
    exclude-favorited: false
    leaving-soon-tv: "Shows (Leaving Soon)"
    leaving-soon-movies: "Movies (Leaving Soon)"
    leaving-soon-type: NONE

  jellyseerr:
    enabled: true
    url: "http://seerr.media.svc.cluster.local:5055"
    match-server: false
