---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: intel-device-plugin-gpu
spec:
  chartRef:
    kind: OCIRepository
    name: intel-device-plugins-gpu
  interval: 1h
  values:
    image:
      hub: docker.io/intel
    initImage:
      hub: docker.io/intel
    name: intel-device-plugin-gpu
    nodeFeatureRule: true
    resources:
      requests:
        cpu: 10m
        memory: 64Mi
      limits:
        memory: 128Mi
    sharedDevNum: 3
