---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
components:
  - ../../../../components/repos/windmill
resources:
  - ./httproute.yaml
  - ./cnp-allow.yaml
  - ./externalsecret.yaml
  - ./externalsecret-workflows.yaml
  - ./helmrelease.yaml
  - ./securitypolicy.yaml
