---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
components:
  - ../../../../components/repos/app-template
resources:
  - ./cnp-allow.yaml
  - ./externalsecret-curator.yaml
  - ./externalsecret.yaml
  - ./helmrelease-curator.yaml
  - ./helmrelease.yaml
configMapGenerator:
  - name: immichkiosk-party-config
    files:
      - config.yaml=./resources/config.yaml
generatorOptions:
  disableNameSuffixHash: true
