{
 "title": "Lovenet Home Assistant Dashboard",
 "time": { "from": "now-3h", "to": "now" },
 "panels": [
  {
   "title": "Sump Pump runs per Day, over a Week",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "hass_sensor_state{\"entity\"=\"sensor.sump_pump_runs_per_day\"}",
     "legendFormat": "Sump Pump Runs"
    },
    {
     "expr": "hass_sensor_precipitation_intensity_in_per_h{domain=\"sensor\", entity=\"sensor.gw1100b_v2_2_3_rain_rate\", instance=\"home-assistant.home.svc.cluster.local:8123\", job=\"home-assistant\"}",
     "legendFormat": "Rain Rate"
    }
   ]
  },
  {
   "title": "Rack Power Draw",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "expr": "upsAdvOutputActivePower{container=\"snmp-exporter\", endpoint=\"http\", instance=\"192.168.5.36\", job=\"snmp-exporter-apc-ups\", namespace=\"observability\", service=\"snmp-exporter-apc-ups\", target=\"apc-ups-1500\"}",
     "legendFormat": "Smart UPS 1500"
    },
    {
     "expr": "upsAdvOutputActivePower{container=\"snmp-exporter\", endpoint=\"http\", instance=\"192.168.5.65\", job=\"snmp-exporter-apc-ups\", namespace=\"observability\", service=\"snmp-exporter-apc-ups\", target=\"apc-ups-3000\"}",
     "legendFormat": "Smart UPS 3000"
    }
   ]
  },
  {
   "title": "Home Power Draw",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "expr": "hass_sensor_power_w{domain=\"sensor\", entity=\"sensor.em16_a1_power\", instance=\"home-assistant.home.svc.cluster.local:8123\"}",
     "legendFormat": "Left Hot"
    },
    {
     "expr": "hass_sensor_power_w{domain=\"sensor\", entity=\"sensor.em16_b1_power\", instance=\"home-assistant.home.svc.cluster.local:8123\"}",
     "legendFormat": "Right Hot"
    }
   ]
  },
  {
   "title": "UPS 1500 Input Voltage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "targets": [
    {
     "expr": "upsAdvInputLineVoltage{container=\"snmp-exporter\", endpoint=\"http\", instance=\"192.168.5.36\", job=\"snmp-exporter-apc-ups\", namespace=\"observability\", service=\"snmp-exporter-apc-ups\", target=\"apc-ups-1500\"}",
     "legendFormat": "Input"
    },
    {
     "expr": "upsAdvInputMaxLineVoltage{container=\"snmp-exporter\", endpoint=\"http\", instance=\"192.168.5.36\", job=\"snmp-exporter-apc-ups\", namespace=\"observability\", service=\"snmp-exporter-apc-ups\", target=\"apc-ups-1500\"}",
     "legendFormat": "Maximum"
    },
    {
     "expr": "upsAdvInputMinLineVoltage{container=\"snmp-exporter\", endpoint=\"http\", instance=\"192.168.5.36\", job=\"snmp-exporter-apc-ups\", namespace=\"observability\", service=\"snmp-exporter-apc-ups\", target=\"apc-ups-1500\"}",
     "legendFormat": "Minimum"
    }
   ]
  },
  {
   "title": "UPS 3000 Input Voltage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "targets": [
    {
     "expr": "upsAdvInputLineVoltage{container=\"snmp-exporter\", endpoint=\"http\", instance=\"192.168.5.65\", job=\"snmp-exporter-apc-ups\", namespace=\"observability\", service=\"snmp-exporter-apc-ups\", target=\"apc-ups-3000\"}",
     "legendFormat": "Input"
    },
    {
     "expr": "upsAdvInputMaxLineVoltage{container=\"snmp-exporter\", endpoint=\"http\", instance=\"192.168.5.65\", job=\"snmp-exporter-apc-ups\", namespace=\"observability\", service=\"snmp-exporter-apc-ups\", target=\"apc-ups-3000\"}",
     "legendFormat": "Maximum"
    },
    {
     "expr": "upsAdvInputMinLineVoltage{container=\"snmp-exporter\", endpoint=\"http\", instance=\"192.168.5.65\", job=\"snmp-exporter-apc-ups\", namespace=\"observability\", service=\"snmp-exporter-apc-ups\", target=\"apc-ups-3000\"}",
     "legendFormat": "Minimum"
    }
   ]
  },
  {
   "title": "UPS Input Voltages",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "targets": [
    {
     "expr": "upsAdvInputLineVoltage{container=\"snmp-exporter\", endpoint=\"http\", instance=\"192.168.5.65\", job=\"snmp-exporter-apc-ups\", namespace=\"observability\", service=\"snmp-exporter-apc-ups\", target=\"apc-ups-3000\"}",
     "legendFormat": "3000 Input"
    },
    {
     "expr": "upsAdvInputLineVoltage{container=\"snmp-exporter\", endpoint=\"http\", instance=\"192.168.5.36\", job=\"snmp-exporter-apc-ups\", namespace=\"observability\", service=\"snmp-exporter-apc-ups\", target=\"apc-ups-1500\"}",
     "legendFormat": "1500 Input"
    }
   ]
  },
  {
   "title": "Rack Power Runtime Remaining",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "upsAdvBatteryRunTimeRemaining{container=\"snmp-exporter\", endpoint=\"http\", instance=\"192.168.5.36\", job=\"snmp-exporter-apc-ups\", namespace=\"observability\", service=\"snmp-exporter-apc-ups\", target=\"apc-ups-1500\"}/100",
     "legendFormat": "Smart UPS 1500"
    },
    {
     "expr": "upsAdvBatteryRunTimeRemaining{container=\"snmp-exporter\", endpoint=\"http\", instance=\"192.168.5.65\", job=\"snmp-exporter-apc-ups\", namespace=\"observability\", service=\"snmp-exporter-apc-ups\", target=\"apc-ups-3000\"}/100",
     "legendFormat": "Smart UPS 3000"
    }
   ]
  },
  {
   "title": "Water Softener",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "bool_on_off" } },
   "targets": [
    {
     "expr": "hass_binary_sensor_state{domain=\"binary_sensor\", entity=\"binary_sensor.water_softener_running\", friendly_name=\"Water Softener Running\", instance=\"home-assistant.home.svc.cluster.local:8123\", job=\"home-assistant\"}",
     "legendFormat": "Water Softener State"
    }
   ]
  },
  {
   "title": "UPS Battery Percentage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "upsAdvBatteryCapacity{target=\"apc-ups-1500\"}",
     "legendFormat": "Smart UPS 1500"
    },
    {
     "expr": "upsAdvBatteryCapacity{target=\"apc-ups-3000\"}",
     "legendFormat": "Smart UPS 3000"
    }
   ]
  },
  {
   "title": "Salt Tank Level",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 72 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "hass_sensor_unit_percent{domain=\"sensor\", entity=\"sensor.iqua_softener_rhw4221_26069_4003_salt_level\", \ninstance=\"home-assistant.home.svc.cluster.local:8123\", job=\"home-assistant\"}",
     "legendFormat": "Level"
    }
   ]
  },
  {
   "title": "Server Disk Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 80 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "hass_sensor_unit_percent{domain=\"sensor\", entity=\"sensor.beast_mnt_mass_storage_used_percent\", friendly_name=\"beast /mnt/mass_storage disk usage\", instance=\"home-assistant.home.svc.cluster.local:8123\", job=\"home-assistant\"}",
     "legendFormat": "beast"
    },
    {
     "expr": "hass_sensor_unit_percent{domain=\"sensor\", entity=\"sensor.brain_mnt_mass_storage_used_percent\", friendly_name=\"brain /mnt/mass_storage disk usage\", instance=\"home-assistant.home.svc.cluster.local:8123\", job=\"home-assistant\"}",
     "legendFormat": "brain"
    }
   ]
  },
  {
   "title": "Security Camera Disk Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 88 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "hass_sensor_unit_percent{domain=\"sensor\", entity=\"sensor.security_storage_mnt_frigate_media_disk_usage\", instance=\"home-assistant.home.svc.cluster.local:8123\", job=\"home-assistant\"}",
     "legendFormat": "security-storage"
    }
   ]
  },
  {
   "title": "Robert Weight",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 96 },
   "fieldConfig": { "defaults": { "unit": "masslb" } },
   "targets": [
    {
     "expr": "hass_sensor_weight_lb{domain=\"sensor\", entity=\"sensor.robert_weight\", instance=\"home-assistant.home.svc.cluster.local:8123\", job=\"home-assistant\"}",
     "legendFormat": "Weight"
    }
   ]
  },
  {
   "title": "Home Temperatures",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 104 },
   "fieldConfig": { "defaults": { "unit": "fahrenheit" } },
   "targets": [
    {
     "expr": "hass_sensor_temperature_celsius{entity=\"sensor.airthings_wave_233964_temperature\"} * 1.8 + 32",
     "legendFormat": "Basement"
    },
    {
     "expr": "hass_sensor_temperature_celsius{entity=\"sensor.family_room_multisensor_temperature_air\"} * 1.8 + 32",
     "legendFormat": "Family Room"
    },
    {
     "expr": "hass_sensor_temperature_celsius{entity=\"sensor.master_bathroom_multisensor_temperature_air\"} * 1.8 + 32",
     "legendFormat": "Master Bathroom"
    },
    {
     "expr": "hass_sensor_temperature_celsius{entity=\"sensor.master_bedroom_multisensor_temperature_air\"} * 1.8 + 32",
     "legendFormat": "Master Bedroom"
    },
    {
     "expr": "hass_sensor_temperature_celsius{entity=\"sensor.multisensor_temperature_air\"} * 1.8 + 32",
     "legendFormat": "Server Room"
    },
    {
     "expr": "hass_sensor_temperature_celsius{entity=\"sensor.office_multisensor_temperature_air\"} * 1.8 + 32",
     "legendFormat": "Office"
    },
    {
     "expr": "hass_sensor_temperature_celsius{entity=\"sensor.t10_thermostat_current_temperature\"} * 1.8 + 32",
     "legendFormat": "Thermostat"
    },
    {
     "expr": "hass_sensor_temperature_celsius{entity=\"sensor.thermostat_remote_sensor_temperature_sensor\"} * 1.8 + 32",
     "legendFormat": "Thermostat Remote"
    }
   ]
  },
  {
   "title": "Radon 1 Day Average",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 112 },
   "fieldConfig": { "defaults": { "unit": "PiC/L" } },
   "targets": [
    {
     "expr": "hass_sensor_unit_pci_per_l{entity=\"sensor.airthings_wave_233964_radon_1_day_average\"}",
     "legendFormat": "Radon"
    },
    {
     "expr": "hass_sensor_atmospheric_pressure_inhg",
     "legendFormat": "Barometric Pressure"
    }
   ]
  }
 ]
}