---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/kustomization-kustomize-v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: kodi-playback-watcher-secrets
spec:
  targetNamespace: media
  path: ./kubernetes/apps/media/kodi-playback-watcher/secrets
  interval: 30m
  timeout: 5m
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: home-ops-kubernetes
    namespace: flux-system
  dependsOn:
    - name: onepassword-connect
      namespace: external-secrets
  healthCheckExprs:
    - apiVersion: external-secrets.io/v1
      kind: ExternalSecret
      current: status.conditions.exists(c, c.type == 'Ready' && c.status == 'True')
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/kustomization-kustomize-v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: kodi-playback-watcher
spec:
  targetNamespace: media
  path: ./kubernetes/apps/media/kodi-playback-watcher/app
  interval: 30m
  timeout: 5m
  prune: true
  wait: false
  sourceRef:
    kind: GitRepository
    name: home-ops-kubernetes
    namespace: flux-system
  dependsOn:
    - name: kodi-playback-watcher-secrets
      namespace: media
