---
apiVersion: mcp.kuadrant.io/v1alpha1
kind: MCPServerRegistration
metadata:
  name: kubectl-tools
  labels:
    mcp.kuadrant.io/managed: 'true'
spec:
  targetRef:
    group: gateway.networking.k8s.io
    kind: HTTPRoute
    name: kubectl-mcp
  toolPrefix: kubectl_
