---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: pump
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: pump-secret
    template:
      engineVersion: v2
      data:
        # App
        POSTGRES_DSN: postgres://{{ .POSTGRES_USER }}:{{ .POSTGRES_PASS }}@postgres-workoutdiary-rw.databases.svc.cluster.local:5432/workoutdiary

        # Postgres Init
        INIT_POSTGRES_DBNAME: workoutdiary
        INIT_POSTGRES_HOST: postgres-workoutdiary-rw.databases.svc.cluster.local
        INIT_POSTGRES_USER: "{{ .POSTGRES_USER }}"
        INIT_POSTGRES_PASS: "{{ .POSTGRES_PASS }}"
        INIT_POSTGRES_SUPER_PASS: "{{ .POSTGRES_SUPER_PASS }}"

  dataFrom:
    - extract:
        key: cloudnative-pg
    - extract:
        key: pump
