---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app pump
spec:
  chartRef:
    kind: OCIRepository
    name: app-template

  interval: 30m
  values:
    controllers:
      pump:
        annotations:
          reloader.stakater.com/auto: "true"

        type: statefulset

        initContainers:
          init-db:
            image:
              repository: ghcr.io/home-operations/postgres-init
              tag: 18.3.0@sha256:6fa1f331cddd2eb0b6afa7b8d3685c864127a81ab01c3d9400bc3ff5263a51cf

            envFrom: &envFrom
              - secretRef:
                  name: pump-secret
        # trigger renovate
        containers:
          pump:
            image:
              repository: ghcr.io/rwlove/pump
              tag: v0.0.68@sha256:8fbc59c5dda9f61c7363507005c31ff6a68846d137161e67d0cf04868662ae59

            envFrom:
              - secretRef:
                  name: pump-secret

            resources:
              requests:
                cpu: 15m
                memory: 128M
              limits:
                memory: 128M

    service:
      frontend:
        ports:
          http:
            port: &httpPort 8080
      api:
        ports:
          http:
            port: &apiPort 8851

    route:
      frontend:
        annotations:
          glance/name: "PUMP"
          glance/show: "true"
          glance/id: "Collaboration"

        hostnames:
          - "{{ .Release.Name }}.${SECRET_DOMAIN}"
        parentRefs:
          - name: internal
            namespace: network
            sectionName: https
        rules:
          - backendRefs:
              - identifier: frontend
                port: *httpPort
