---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: mealie-mcp
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: mealie-mcp-secret
    creationPolicy: Owner
    template:
      data:
        MEALIE_API_KEY: "{{ .mealie_mcp_token }}"
  dataFrom:
    - extract:
        key: mealie
      rewrite:
        - regexp:
            source: "(.*)"
            target: "mealie_$1"
