---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app medikeep
spec:
  chartRef:
    kind: OCIRepository
    name: app-template

  interval: 30m
  values:
    controllers:
      medikeep:
        pod:
          securityContext:
            fsGroup: 999
            fsGroupChangePolicy: OnRootMismatch

            runAsGroup: 999
            # runAsNonRoot: true
            runAsUser: 999
        annotations:
          reloader.stakater.com/auto: "true"

        type: statefulset

        initContainers:
          init-db:
            image:
              repository: ghcr.io/home-operations/postgres-init
              tag: 18.4.0@sha256:ebd9d30add17acdf935d73eb004758c7dfd9388aaa605fda70ad74378ab92aec

            envFrom: &envFrom
              - secretRef:
                  name: medikeep

        containers:
          app:
            image:
              repository: ghcr.io/afairgiant/medikeep
              tag: v0.67.0@sha256:f842744341fbab48e8d8404944bacdc64e5ef529130cdba13067e7ced21e88a4

            env:
              LOG_LEVEL: "info"
              SSO_ENABLED: "false"
              PUID: 999
              PGID: 999
              MPLCONFIGDIR: /app/matplotlib

            envFrom: *envFrom
            probes:
              startup:
                enabled: false


            resources:
              requests:
                cpu: 15m
                memory: 320M
              limits:
                memory: 320M

            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities:
                drop:
                  - ALL

    service:
      app:
        controller: medikeep
        ports:
          react:
            port: &reactPort 8000
          fast:
            port: &fastAPI 8005

    route:
      app:
        annotations:
          glance/name: "MediKeep"
          glance/show: "true"
          # glance/icon: "https://cdn.jsdelivr.net/gh/homarr-labs/dashboard-icons/png/paperless-ngx.png"
          glance/id: "Collaboration"

        hostnames:
          - "{{ .Release.Name }}.${SECRET_DOMAIN}"
        parentRefs:
          - name: internal
            namespace: network
            sectionName: https
        rules:
          - backendRefs:
              - identifier: app
                port: *reactPort

    persistence:
      backups:
        type: emptyDir
        globalMounts:
          - path: /app/backups
      logs:
        type: emptyDir
        globalMounts:
          - path: /app/logs
      matplotlib:
        type: emptyDir
        globalMounts:
          - path: /app/matplotlib
      uploads:
        type: emptyDir
        globalMounts:
          - path: /app/uploads

    serviceMonitor:
      app:
        serviceName: *app
        endpoints:
          - port: metrics
            scheme: http
            path: /metrics
            interval: 1m
            scrapeTimeout: 10s
