---
# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/master-standalone-strict/persistentvolumeclaim-v1.json
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: collab
  name: medikeep-uploads-pvc
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 5Gi
  volumeName: medikeep-uploads-pv
  storageClassName: medikeep-uploads-storage-class

---
# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/master-standalone-strict/persistentvolume-v1.json
apiVersion: v1
kind: PersistentVolume
metadata:
  name: medikeep-uploads-pv
  labels:
    type: longhorn
    recurring-job-group.longhorn.io/weekly-backup: enabled
    recurring-job-group.longhorn.io/daily-snapshot: enabled
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: medikeep-uploads-storage-class
  csi:
    driver: driver.longhorn.io
    fsType: ext4
    volumeAttributes:
      numberOfReplicas: "2"
      staleReplicaTimeout: "2880"
    volumeHandle: pvc-c955fca8-0e2b-4429-9c89-49c86b4f54b3
