---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: medikeep-data-pvc
  labels:
    type: longhorn
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 5Gi
  volumeName: medikeep-data-pv
  storageClassName: medikeep-data-storage-class

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: medikeep-data-pv
  labels:
    type: longhorn
    recurring-job-group.longhorn.io/weekly-backup: enabled
    recurring-job-group.longhorn.io/daily-snapshot: enabled
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: medikeep-data-storage-class
  csi:
    driver: driver.longhorn.io
    fsType: xfs
    volumeAttributes:
      numberOfReplicas: "2"
      staleReplicaTimeout: "2880"
    volumeHandle: medikeep-data-xfs
