---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./cluster-config.yaml
  - ./externalsecret.yaml
  - ./github/
  - ./helmrelease.yaml
  - ./podmonitor.yaml
  - ./prometheusrule.yaml
configMapGenerator:
  - files:
      - values.yaml=./helm/values.yaml
    name: flux-instance-values
configurations:
  - ./helm/kustomizeconfig.yaml
