---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: downloads
resources:
  - ./namespace.yaml
  - ./jdownloader2/ks.yaml
  - ./jdownloader2-oauth2-proxy/ks.yaml
  - ./prowlarr/ks.yaml
  - ./prowlarr-oauth2-proxy/ks.yaml
  - ./qbittorrent/ks.yaml
  - ./qbittorrent-oauth2-proxy/ks.yaml
  - ./sabnzbd/ks.yaml
  - ./sabnzbd-oauth2-proxy/ks.yaml
  - ./slskd/ks.yaml
  - ./slskd-oauth2-proxy/ks.yaml
