---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app jdownloader2
spec:
  chartRef:
    kind: OCIRepository
    name: app-template
  interval: 30m

  values:
    controllers:
      main:
        annotations:
          reloader.stakater.com/auto: "true"
        type: statefulset
        # pod:
        #   securityContext:
        #     runAsUser: 568
        #     runAsGroup: 568
        #     fsGroup: 568
        #     fsGroupChangePolicy: OnRootMismatch
        #     supplementalGroups: [10000]
        containers:
          main:
            image:
              repository: ghcr.io/jlesage/jdownloader-2
              tag: v26.03.1@sha256:3d6cb102bd9bacff12ab1ca5136a38cb8f93d6595a7ccf5bce60aac4df138ebd

            resources:
              requests:
                cpu: 100m
                memory: 1G
              limits:
                memory: 1G

    persistence:
      config:
        existingClaim: jdownloader-config-pvc
        globalMounts:
          - path: /config

      downloads:
        existingClaim: jdownloader-downloads-pvc
        globalMounts:
          - path: /output

    route:
      main:
        annotations:
          glance/name: "JDownloader"
          glance/show: "true"
          glance/icon: "https://cdn.jsdelivr.net/gh/homarr-labs/dashboard-icons/png/jdownloader2.png"
          glance/id: "Downloads"
        hostnames:
          - "downloader.${SECRET_DOMAIN}"
        parentRefs:
          - name: internal
            namespace: network
            sectionName: https
        rules:
          - backendRefs:
              - identifier: main
                port: *httpPort

    service:
      main:
        controller: main
        ports:
          http:
            port: &httpPort 5800
