---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: downloads-gateway
spec:
  interval: 30m
  chart:
    spec:
      # renovate: registryUrl=https://angelnu.github.io/helm-charts
      chart: pod-gateway
      version: 7.1.1
      sourceRef:
        kind: HelmRepository
        name: angelnu

  values:
    controllers:
      main:
        type: statefulset

        annotations:
          reloader.stakater.com/auto: "true"

        containers:
          main:
            image:
              repository: ghcr.io/angelnu/pod-gateway
              tag: v1.13.0@sha256:a5b032e15f7570493977b330a5a86dcffebb807d35685ad803e47afb62d105f2

          gluetun:
            enabled: true # necessary
            image:
              # TODO: Replace with ghcr.io/qdm12/gluetun when a versioned tag is available
              repository: ghcr.io/qdm12/gluetun
              tag: v3.41.1@sha256:1a5bf4b4820a879cdf8d93d7ef0d2d963af56670c9ebff8981860b6804ebc8ab

            env:
              - name: VPN_INTERFACE
                value: wg0
              - name: FIREWALL
                value: "off"
              - name: DOT
                value: "off"
              - name: HEALTH_TARGET_ADDRESS
                value: "1.1.1.1"
              - name: HEALTH_VPN_DURATION_INITIAL
                value: 30s
            envFrom:
              - secretRef:
                  name: downloads-gateway-vpnconfig

            securityContext:
              privileged: true
              capabilities:
                add:
                  - NET_ADMIN

            resources:
              requests:
                cpu: 15m
                memory: 256M
              limits:
                memory: 256M

          netshoot:
            enabled: true
            image:
              repository: ghcr.io/nicolaka/netshoot
              tag: v0.15

            command:
              - /bin/sh
              - -c
              - sleep infinity

            securityContext:
              privileged: true
              capabilities:
                add:
                  - NET_ADMIN
                  - NET_RAW

            resources:
              requests:
                cpu: 15m
                memory: 30M
              limits:
                memory: 30M
      webhook:
        type: statefulset
        pod:
          # The sidecar containers inserted by the webhook will use this DNS config
          dnsConfig:
            options:
              - name: ndots
                value: '1'
        # Configure the main controller - this runs the VPN server
        containers:
          main:
            image:
              repository: ghcr.io/angelnu/gateway-admision-controller
              tag: v3.12.0
            securityContext:
              privileged: true # Required for mknod/device access
              capabilities:
                add:
                  - NET_ADMIN
                  - NET_RAW

    networkpolicies:
      main:
        enabled: false 
        
    DNS: 172.16.1.1

    routed_namespaces:
      - downloads

    settings:
      NOT_ROUTED_TO_GATEWAY_CIDRS: 10.42.0.0/16 10.43.0.0/16 192.168.0.0/16
      VPN_BLOCK_OTHER_TRAFFIC: true
      VPN_INTERFACE: wg0
      VPN_LOCAL_CIDRS: 10.42.0.0/16 10.43.0.0/16 192.168.0.0/16
      DNS_LOCAL_CIDRS: "${SECRET_DOMAIN} cluster.local local"
      VPN_TRAFFIC_PORT: "51820"
      VXLAN_ID: 43
      VXLAN_IP_NETWORK: 172.16.1

    # -- settings to expose ports, usually through a VPN provider.
    # NOTE: if you change it you will need to manually restart the gateway POD
    publicPorts:
    - hostname: qbittorrent
      IP: 10
      ports:
      - type: udp
        port: 24589 #can I use a var from externalsecrets?
      - type: tcp
        port: 24589 #same here
