---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app sonarr
spec:
  chartRef:
    kind: OCIRepository
    name: app-template

  interval: 30m
  values:
    controllers:
      main:
        pod:
          securityContext:
            fsGroup: 1001
            fsGroupChangePolicy: OnRootMismatch
            runAsGroup: 1001
            runAsUser: 1000

        annotations:
          reloader.stakater.com/auto: "true"

        type: statefulset
        containers:
          main:
            image:
              repository: ghcr.io/home-operations/sonarr
              tag: rolling@sha256:83607d2b741ec9469db09489e88c473ae6fdf7d85f3b55d4fa809b43e25a2a6c

            env:
              SONARR__APP__INSTANCENAME: Sonarr
              SONARR__AUTH__METHOD: External
              SONARR__AUTH__REQUIRED: DisabledForLocalAddresses
              SONARR__LOG__DBENABLED: "False"
              SONARR__LOG__LEVEL: info
              SONARR__SERVER__PORT: &httpPort 8989
              SONARR__UPDATE__BRANCH: develop

            envFrom:
              - secretRef:
                  name: *app


            resources:
              requests:
                cpu: 15m
                memory: 1G
              limits:
                memory: 1G

            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities: {drop: ["ALL"]}
    service:
      main:
        controller: main
        ports:
          http:
            port: *httpPort

    route:
      main:
        annotations:
          glance/name: "Sonarr"
          glance/show: "true"
          glance/icon: "https://cdn.jsdelivr.net/gh/homarr-labs/dashboard-icons/png/sonarr.png"
          glance/id: "Media"

        hostnames:
          - "{{ .Release.Name }}.${SECRET_DOMAIN}"
        parentRefs:
          - name: internal
            namespace: network
            sectionName: https
        rules:
          - backendRefs:
              - identifier: main
                port: *httpPort
    persistence:
      config:
        existingClaim: sonarr-config-pvc

      downloads:
        existingClaim: sonarr-downloads

      media:
        existingClaim: sonarr-media

      sabnzbd:
        existingClaim: sonarr-sabnzbd-downloads
