---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: longhorn
spec:
  interval: 30m
  chart:
    spec:
      # renovate: registryUrl=https://charts.longhorn.io
      chart: longhorn
      version: 1.11.0
      sourceRef:
        kind: HelmRepository
        name: longhorn-charts
  values:
    # preUpgradeChecker and image sections are workarounds until 1.11.1 is released
    # https://github.com/longhorn/longhorn/issues/12573
    preUpgradeChecker:
      jobEnabled: false
      upgradeVersionCheck: false
    image:
      longhorn:
        instanceManager:
          tag: v1.11.0-hotfix-1
        manager:
          tag: v1.11.0-hotfix-1

    global:
      imageRegistry: docker.io

    persistence:
      defaultClass: false
      defaultClassReplicaCount: 1
      reclaimPolicy: Retain

    defaultSettings:
      defaultReplicaCount: 2
      replicaAutoBalance: best-effort
      defaultDataLocality: best-effort
      backupTarget: "nfs://beast:/mnt/mass_storage/longhorn-backups"
      createDefaultDiskLabeledNodes: true
      storageMinimalAvailablePercentage: 10
      kubernetesClusterAutoscalerEnabled: true

    longhornManager:
      securityContext:
        privileged: true
