---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/kustomization-kustomize-v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: mcp-gateway
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: mcp-gateway
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2
      kind: HelmRelease
      name: mcp-gateway
      namespace: ai
  interval: 1h
  path: "./kubernetes/apps/ai/kuadrant-mcp-gateway/app"
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-ops-kubernetes
    namespace: flux-system
  targetNamespace: ai
  timeout: 5m
