directory: /media
library: /config/library.db

import:
  incremental: yes
  incremental_skip_later: yes
  quiet: yes
  quiet_fallback: skip
  write: yes
  copy: no
  move: no
  log: /config/import.log

plugins:
  - fetchart # https://beets.readthedocs.io/en/stable/plugins/fetchart.html
  - embedart # https://beets.readthedocs.io/en/stable/plugins/embedart.html
  - musicbrainz # https://beets.readthedocs.io/en/stable/plugins/musicbrainz.html

chroma:
  auto: yes

fetchart:
  auto: yes
  minwidth: 500
  maxwidth: 1200
  sources: coverartarchive itunes amazon albumart wikipedia

embedart:
  auto: yes
  ifempty: yes
  maxwidth: 500
  remove_art_file: no
