directory: /media
library: /config/library.db

import:
  incremental: yes
  incremental_skip_later: yes
  quiet: yes
  quiet_fallback: skip
  write: yes
  copy: no
  move: no
  log: /config/import.log

plugins: chroma fetchart embedart lastgenre plexupdate

chroma:
  auto: yes

acoustid:
  apikey: ${ACOUSTID_API_KEY}

fetchart:
  auto: yes
  minwidth: 500
  maxwidth: 1200
  sources: coverartarchive itunes amazon albumart wikipedia

embedart:
  auto: yes
  ifempty: yes
  maxwidth: 500
  remove_art_file: no

lastgenre:
  auto: yes
  count: 5
  canonical: yes
  prefer_specific: yes
  source: album
  min_weight: 10

#plex:
#  host: plex.default.svc.cluster.local
#  token: ${PLEX_TOKEN}
