---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./cnp-allow.yaml
  - ./cronjob-offsite-backup.yaml
  - ./externalsecret-offsite-backup.yaml
  - ./externalsecret.yaml
  - ./helmrelease.yaml
  - ./helmrepository.yaml
  - ./httproute.yaml
  - ./nfs-pvc.yaml
