---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: videodupfinder-brain-pv
  labels:
    type: nfs
spec:
  storageClassName: videodupfinder-brain-storage-class
  capacity:
    storage: 20Ti
  accessModes:
    - ReadWriteOnce
  nfs:
    server: "${NFS_HOST_0}"
    path: /mnt/mass_storage

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: videodupfinder-brain-pvc
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 20Ti
  volumeName: videodupfinder-brain-pv
  storageClassName: videodupfinder-brain-storage-class
