---
# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/master-standalone-strict/persistentvolume-v1.json
apiVersion: v1
kind: PersistentVolume
metadata:
  name: videodupfinder-scan-pv
  labels:
    type: nfs
spec:
  storageClassName: videodupfinder-scan-storage-class
  capacity:
    storage: 20Ti
  accessModes:
    - ReadWriteOnce
  nfs:
    server: "${NFS_HOST}"
    path: "${NFS_PATH}"

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: videodupfinder-scan-pvc
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 20Ti
  volumeName: videodupfinder-scan-pv
  storageClassName: videodupfinder-scan-storage-class
