---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app prowlarr
spec:
  chartRef:
    kind: OCIRepository
    name: app-template
  interval: 30m

  values:
    controllers:
      main:
        pod:
          securityContext:
            fsGroup: 568
            fsGroupChangePolicy: "OnRootMismatch"

            runAsGroup: 568
            runAsUser: 568
        annotations:
          reloader.stakater.com/auto: "true"
        type: statefulset
        containers:
          main:
            image:
              repository: ghcr.io/home-operations/prowlarr
              tag: rolling@sha256:da6b1f914ad22778c347d554a59b6e40110f654b40528c8de516616382db5148

            env:
              PROWLARR__INSTANCE_NAME: Prowlarr
              PROWLARR__LOG_LEVEL: info

              PROWLARR__PORT: &httpPort 80
            envFrom:
              - secretRef:
                  name: *app

            resources:
              requests:
                cpu: 15m
                memory: 300M
              limits:
                memory: 300M

            securityContext:
              capabilities:
                add:
                  - NET_ADMIN
                  - NET_RAW

              privileged: true
    service:
      main:
        ports:
          http:
            port: *httpPort

    route:
      main:
        annotations:
          glance/icon: "https://cdn.jsdelivr.net/gh/homarr-labs/dashboard-icons/png/prowlarr.png"
          glance/id: "Downloads"
          glance/name: "Prowlarr"
          glance/show: "true"
        hostnames:
          - "{{ .Release.Name }}.${SECRET_DOMAIN}"
        parentRefs:
          - name: internal
            namespace: network
            sectionName: https
        rules:
          - backendRefs:
              - identifier: main
                port: *httpPort

    persistence:
      config:
        existingClaim: prowlarr-config-pvc
