---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
components:
  - ../../../../components/repos/app-template
resources:
  - ./externalsecret.yaml
  - ./helmrelease.yaml
configMapGenerator:
  - files:
      - hooks.yaml=./resources/hooks.yaml
      - github-renovate-operator.sh=./resources/github-renovate-operator.sh
    name: webhook-configmap
generatorOptions:
  annotations:
    kustomize.toolkit.fluxcd.io/substitute: disabled
  disableNameSuffixHash: true
