---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kiali
spec:
  chart:
    spec:
      chart: kiali-operator
      sourceRef:
        kind: HelmRepository
        name: kiali
      version: 2.25.0
  interval: 5m
  values:
    # https://artifacthub.io/packages/olm/community-operators/kiali
    # https://github.com/kiali/helm-charts/blob/master/kiali-operator/values.yaml
    cr:
      annotations: {}
      create: true
      name: kiali
      namespace: istio-system
      spec:
        auth:
          strategy: anonymous
        deployment:
          ingress:
            enabled: false
          replicas: 1
        external_services:
          grafana:
            enabled: true
            in_cluster_url: http://grafana.observability.svc.cluster.local/
            url: https://grafana.${SECRET_DOMAIN}
          prometheus:
            url: http://kube-prometheus-stack-prometheus.observability.svc.cluster.local:9090
        istio_labels:
          app_label_name: "app.kubernetes.io/name"
          version_label_name: "app.kubernetes.io/version"
        istio_namespace: istio-system
        server:
          web_fqdn: kiali.${SECRET_DOMAIN}
          web_port: "443"
          web_root: /
          web_schema: https
    replicaCount: 2
    resources:
      requests:
        cpu: "10m"
        memory: "64Mi"
