---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app smtp-relay
spec:
  chartRef:
    kind: OCIRepository
    name: app-template

  interval: 30m
  values:
    controllers:
      main:

        pod:
          securityContext:
            fsGroup: 568
            fsGroupChangePolicy: OnRootMismatch

            runAsGroup: 568
            runAsUser: 568
          topologySpreadConstraints:
            - maxSkew: 1
              topologyKey: kubernetes.io/hostname
              whenUnsatisfiable: DoNotSchedule
              labelSelector:
                matchLabels:
                  app.kubernetes.io/name: *app

        annotations:
          reloader.stakater.com/auto: "true"

        replicas: 1

        type: statefulset
        containers:
          main:
            image:
              repository: ghcr.io/foxcpp/maddy
              tag: 0.9.3@sha256:2ce7ce6343816c8c96056776dd06660987d97ada96d31163cdd968d62e496a12

            env:
              DEBUG: "true"
              SMTP_DOMAIN: "${SECRET_DOMAIN}"
              SMTP_SERVER: "smtp.mailgun.org"
              SMTP_USERNAME: "postmaster@${SECRET_DOMAIN}"
              SMTP_PORT: "465"
              SMTP_RELAY_SMTP_PORT: &port 2525
              SMTP_RELAY_METRICS_PORT: &metricsPort 8080

            envFrom:
              - secretRef:
                  name: *app

            resources:
              requests:
                cpu: 15m
                memory: 64M
              limits:
                memory: 64M

            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities: {drop: ["ALL"]}
    service:
      main:
        type: LoadBalancer
        annotations:
          lbipam.cilium.io/ips: ${SVC_SMTP_RELAY_ADDR}
        externalTrafficPolicy: Local
        ports:
          metrics:
            port: *metricsPort
          smtp:
            port: *port
    persistence:
      cache:
        type: emptyDir
        medium: Memory
      config:
        type: configMap
        name: *app
        globalMounts:
          - path: /data/maddy.conf
            subPath: maddy.conf
            readOnly: true


    serviceMonitor:
      main:
        serviceName: *app
        endpoints:
          - port: metrics

