---
image:
  repository: ghcr.io/xunholy/kustomize-mutating-webhook
  tag: 0.11.0@sha256:963587b43bbef2651a2bbe137a93e4a7f60f46aba83b25dc368a5f0f9e677bca
replicas: 1
certManager:
  enabled: true
configMaps:
  - create: false
    name: cluster-config
secrets:
  - create: false
    name: cluster-secrets
env:
  LOG_LEVEL: debug
networkpolicy:
  create: false
podDisruptionBudget:
  enabled: false
securityContext:
  allowPrivilegeEscalation: false
  readOnlyRootFilesystem: true
  capabilities:
    drop:
      - ALL
  seccompProfile:
    type: RuntimeDefault
service:
  headless: false
