---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app sabnzbd
spec:
  chartRef:
    kind: OCIRepository
    name: app-template
  interval: 30m

  values:
    controllers:
      main:
        pod:
          securityContext:
            fsGroup: 1001
            fsGroupChangePolicy: OnRootMismatch
            runAsGroup: 1001
            runAsUser: 1000
            runAsNonRoot: true

        annotations:
          reloader.stakater.com/auto: "true"
        type: statefulset
        containers:
          main:
            image:
              repository: ghcr.io/home-operations/sabnzbd
              tag: rolling@sha256:c22ada9eb6f6306a4e94d3372c784a5330818f2021b2fa9233ff4ae92d9f3582

            env:
              HAS_IPV6: "false"
              SABNZBD__HOST_WHITELIST_ENTRIES: >-
                sabnzbd,
                sabnzbd.downloads,
                sabnzbd.downloads.svc,
                sabnzbd.downloads.svc.cluster,
                sabnzbd.downloads.svc.cluster.local,
                sabnzbd.${SECRET_DOMAIN}
              SABNZBD__PORT: &httpPort 8080

            envFrom:
              - secretRef:
                  name: *app

            probes:
              liveness: &probes
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /api?mode=version
                    port: *httpPort
                  failureThreshold: 3
                  initialDelaySeconds: 0
                  periodSeconds: 10
                  timeoutSeconds: 1
              readiness: *probes
              startup:
                enabled: false

            resources:
              requests:
                cpu: 15m
                memory: 1.3G
              limits:
                memory: 1.3G

    service:
      main:
        ports:
          http:
            port: *httpPort
    route:
      main:
        annotations:
          glance/name: "Sabnzbd"
          glance/show: "true"
          glance/icon: "https://cdn.jsdelivr.net/gh/homarr-labs/dashboard-icons/png/sabnzbd.png"
          glance/id: "Downloads"
        hostnames:
          - "{{ .Release.Name }}.${SECRET_DOMAIN}"
        parentRefs:
          - name: internal
            namespace: network
            sectionName: https
        rules:
          - backendRefs:
              - kind: Service
                name: sabnzbd-oauth2-proxy
                port: 4180

    persistence:
      complete:
        existingClaim: sabnzbd-complete-pvc

      config:
        existingClaim: sabnzbd-config-pvc

      downloads:
        existingClaim: sabnzbd-downloads-pvc

      incomplete:
        existingClaim: sabnzbd-incomplete-pvc
