---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: obsidian-couchdb
spec:
  chartRef:
    kind: OCIRepository
    name: app-template

  interval: 30m
  values:
    controllers:
      main:
        pod:
          securityContext:
            fsGroup: ${APP_GID}
            fsGroupChangePolicy: "OnRootMismatch"

            runAsGroup: ${APP_GID}
            runAsUser: ${APP_UID}
        annotations:
          reloader.stakater.com/auto: "true"

        type: statefulset

        initContainers:
          init-config:
            image:
              repository: public.ecr.aws/docker/library/busybox
              tag: latest@sha256:1487d0af5f52b4ba31c7e465126ee2123fe3f2305d638e7827681e7cf6c83d5e
              pullPolicy: IfNotPresent
            command:
              - "/bin/sh"
              - "-c"
              - "cp /tmp/config/*.ini /opt/couchdb/etc/default.d/; ls -lrt /opt/couchdb/etc/default.d;"

        containers:
          main:
            image:
              repository: docker.io/library/couchdb
              tag: 3.5.1@sha256:0ff2633acd380777f2c65af22eabb1d961569e05e25b12c5239b00a7f8b56d54
            env:
              COUCHDB_USER:
                valueFrom:
                  secretKeyRef:
                    name: obsidian-couchdb-secret
                    key: couchdb-user
              COUCHDB_PASSWORD:
                valueFrom:
                  secretKeyRef:
                    name: obsidian-couchdb-secret
                    key: couchdb-password
            resources:
              requests:
                cpu: 15m
                memory: 200M
              limits:
                memory: 200M

    service:
      main:
        controller: main
        ports:
          http:
            port: &httpPort 5984

    route:
      main:
        hostnames:
          - "obsidian.${SECRET_DOMAIN}"
        parentRefs:
          - name: external
            namespace: network
            sectionName: https
        rules:
          - backendRefs:
              - identifier: main
                port: *httpPort

    persistence:
      config:
        type: configMap
        name: obsidian-couchdb-configmap
        advancedMounts:
          main:
            init-config:
              - path: /tmp/config
      config-storage:
        type: emptyDir
        globalMounts:
          - path: /opt/couchdb/etc/default.d
      data:
        existingClaim: obsidian-data-pvc
        advancedMounts:
          main:
            main:
              - path: /opt/couchdb/data
