---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app wg-easy
spec:
  chartRef:
    kind: OCIRepository
    name: app-template

  interval: 30m
  values:
    controllers:
      wg-easy:
        annotations:
          reloader.stakater.com/auto: "true"

        containers:
          app:
            image:
              repository: ghcr.io/wg-easy/wg-easy
              tag: "15"

            env:
              INIT_ALLOWED_IPS: "192.168.0.0/16, 10.45.0.0/24"
              INIT_DNS: 192.168.1.1
              INIT_HOST: vpn.${SECRET_DOMAIN}
              INIT_IPV4_CIDR: 10.99.0.0/24
              INIT_PERSISTENT_KEEPALIVE: "25"
              INIT_PORT: &wgPort 51820
              INIT_USERNAME: admin
              PORT: &uiPort 51821

            envFrom:
              - secretRef:
                  name: wg-easy-secret

            probes:
              liveness: &probes
                enabled: true
                custom: true
                spec:
                  tcpSocket:
                    port: *uiPort
                  initialDelaySeconds: 10
                  periodSeconds: 30
              readiness: *probes
              startup:
                enabled: false

            resources:
              requests:
                cpu: 10m
                memory: 64Mi
              limits:
                memory: 256Mi

            securityContext:
              privileged: true
    service:
      app:
        type: LoadBalancer
        annotations:
          lbipam.cilium.io/ips: ${SVC_WG_EASY_ADDR}
        controller: wg-easy
        externalTrafficPolicy: Cluster
        ports:
          wireguard:
            port: *wgPort
            protocol: UDP
      web:
        type: ClusterIP
        controller: wg-easy
        ports:
          http:
            port: *uiPort

    route:
      web:
        hostnames:
          - "wg-easy.${SECRET_DOMAIN}"
        parentRefs:
          - name: internal
            namespace: network
            sectionName: https
        rules:
          - backendRefs:
              - identifier: web
                port: *uiPort
    persistence:
      config:
        accessMode: ReadWriteOnce
        size: 1Gi
        storageClass: ceph-block
        globalMounts:
          - path: /etc/wireguard
