---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: arc-home-ops
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: gha-runner-scale-set
  driftDetection:
    mode: enabled
  values:
    runnerScaleSetName: arc-runner-set-home-ops

    githubConfigUrl: https://github.com/rwlove/home-ops

    minRunners: 1
    maxRunners: 6

    containerMode:
      type: kubernetes
      kubernetesModeWorkVolumeClaim:
        accessModes:
          - ReadWriteOnce
        storageClassName: openebs-hostpath
        resources:
          requests:
            storage: 25Gi

    controllerServiceAccount:
      name: actions-runner-controller
      namespace: actions-runner-system

    template:
      spec:
        containers:
          - name: runner
            image: ghcr.io/home-operations/actions-runner:2.334.0@sha256:95d91d7f8d241e319ef2f4fec08f417aa1606b96fbb327643f75c303acd30002
            command: ["/home/runner/run.sh"]
            env:
              - name: NODE_IP
                valueFrom:
                  fieldRef:
                    fieldPath: status.hostIP
              - name: ACTIONS_RUNNER_REQUIRE_JOB_CONTAINER
                value: "false"

  valuesFrom:
    - kind: Secret
      name: actions-runner-controller-auth
      valuesKey: github_app_id
      targetPath: githubConfigSecret.github_app_id
    - kind: Secret
      name: actions-runner-controller-auth
      valuesKey: github_app_installation_id
      targetPath: githubConfigSecret.github_app_installation_id
    - kind: Secret
      name: actions-runner-controller-auth
      valuesKey: github_app_private_key
      targetPath: githubConfigSecret.github_app_private_key
