---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/kustomization-kustomize-v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: vector-aggregator
spec:
  targetNamespace: observability
  path: ./kubernetes/apps/observability/vector/aggregator
  interval: 30m
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: home-ops-kubernetes
    namespace: flux-system
  dependsOn:
    - name: onepassword-connect
      namespace: external-secrets
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/kustomization-kustomize-v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: vector-agent
spec:
  targetNamespace: observability
  path: ./kubernetes/apps/observability/vector/agent
  interval: 30m
  prune: true
  wait: false # no flux ks dependents
  sourceRef:
    kind: GitRepository
    name: home-ops-kubernetes
    namespace: flux-system
  dependsOn:
    - name: vector-aggregator
      namespace: observability
