---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/kustomization-kustomize-v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: webhook
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: webhook
  targetNamespace: selfhosted
  path: "./kubernetes/apps/selfhosted/webhook/app"
  interval: 1h
  timeout: 5m
  prune: true
  wait: false
  sourceRef:
    kind: GitRepository
    name: home-ops-kubernetes
    namespace: flux-system
