---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/kustomization-kustomize-v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app windmill-oauth2-proxy
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  targetNamespace: home
  path: ./kubernetes/apps/home/windmill-oauth2-proxy/app
  interval: 1h
  timeout: 5m
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: home-ops-kubernetes
    namespace: flux-system
  dependsOn:
    - name: authelia
      namespace: auth
    - name: windmill
      namespace: home
  retryInterval: 2m
