---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/postgresql.cnpg.io/cluster_v1.json
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: postgres-videodupfinder
spec:
  instances: 3

  imageName: ghcr.io/cloudnative-pg/postgresql:17.5

  primaryUpdateStrategy: unsupervised

  postgresql:
    parameters:
      pg_stat_statements.max: "10000"
      pg_stat_statements.track: all
      timezone: "America/New_York"

  storage:
    size: 5Gi
    storageClass: ceph-block

  resources:
    requests:
      cpu: 100m
      memory: 512Mi

  enableSuperuserAccess: true
  superuserSecret:
    name: cloudnative-pg

  monitoring:
    enablePodMonitor: true

  plugins:
    - name: barman-cloud.cloudnative-pg.io
      isWALArchiver: true
      parameters: &params
        barmanObjectName: garage-videodupfinder
        serverName: postgres-videodupfinder-backup

  externalClusters:
    - name: source
      plugin:
        name: barman-cloud.cloudnative-pg.io
        parameters: *params
