---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
components:
  - ../../../../components/repos/app-template
resources:
  - ./securitypolicy-hai.yaml
  - ./httproute-hai.yaml
  - ./backendtrafficpolicy.yaml
  - ./cnp-allow.yaml
  - ./cnp-evals.yaml
  - ./cronjob-evals.yaml
  - ./externalsecret.yaml
  - ./helmrelease.yaml
  - ./prometheusrule.yaml
  - ./pvc.yaml
  - ./route-approval.yaml
  - ./servicemonitor.yaml
