---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/kustomization-kustomize-v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app ghostfolio-mcp
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  targetNamespace: ai
  path: ./kubernetes/apps/ai/ghostfolio-mcp/app
  interval: 1h
  timeout: 5m
  wait: false
  dependsOn:
    - name: ghostfolio
      namespace: selfhosted
    - name: onepassword-connect
      namespace: external-secrets
  retryInterval: 2m
