---
# TODO: apply schema
apiVersion: mcp.kuadrant.io/v1alpha1
kind: MCPServerRegistration
metadata:
  name: omada-tools
  labels:
    mcp.kuadrant.io/managed: "true"
spec:
  targetRef:
    group: gateway.networking.k8s.io
    kind: HTTPRoute
    name: omada-mcp
  prefix: omada_
