---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app suggestarr
spec:
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: app-template

  values:
    controllers:
      main:
        type: statefulset
        annotations:
          reloader.stakater.com/auto: "true"

        pod:
          securityContext:
            runAsUser: 1000
            runAsGroup: 1001
            fsGroup: 1001
            fsGroupChangePolicy: "OnRootMismatch"
            supplementalGroups:
              - 100

        containers:
          main:
            image:
              repository: docker.io/ciuse99/suggestarr
              tag: v2.3.1@sha256:f1f587a66b362a82903e0644733455ef2400432d58ad7efa6fd0b7a6d79e522c

            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities: {drop: ["ALL"]}

            resources:
              requests:
                cpu: 15m
                memory: 1G
              limits:
                memory: 1G

    service:
      main:
        controller: main
        ports:
          http:
            port: &port 5000

    route:
      main:
        hostnames:
          - "{{ .Release.Name }}.${SECRET_DOMAIN}"
        parentRefs:
          - name: internal
            namespace: network
            sectionName: https
        rules:
          - backendRefs:
              - identifier: main
                port: *port
        annotations:
          startpunkt.ullberg.us/enable: "true"
          startpunkt.ullberg.us/name: "TV Selection"
          startpunkt.ullberg.us/icon: mdi:television-classic
          startpunkt.ullberg.us/group: "media"
          startpunkt.ullberg.us/instance: "admin"

    persistence:
      config:
        existingClaim: suggestarr-config-pvc
        globalMounts:
          - path: /app/config/config_files
      tmpfs:
        type: emptyDir
        advancedMounts:
          main:
            main:
              - path: /tmp
