---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/gateway.networking.k8s.io/httproute_v1.json
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: netbox
  annotations:
    glance/name: "NetBox"
    glance/show: "true"
    glance/icon: "https://cdn.jsdelivr.net/gh/homarr-labs/dashboard-icons/png/netbox-dark.png"
    glance/id: "Home Automation"
spec:
  hostnames: ["netbox.${SECRET_DOMAIN}"]
  parentRefs:
    - name: internal
      namespace: network
      sectionName: https
  rules:
    - backendRefs:
        - name: netbox
          namespace: home
          port: 80
      matches:
        - path:
            type: PathPrefix
            value: /
