---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/k8s.cni.cncf.io/networkattachmentdefinition_v1.json
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: aquapured-iot-static
spec:
  config: |
    {
    "cniVersion": "0.3.1",
    "type": "macvlan",
    "master": "enp1s0.20",
    "mode": "bridge",
    "ipam": {
    "type": "static",
    "addresses": [
    {
    "address": "10.10.20.105/24"
    }
    ]
    }
    }
