---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
components:
  - ../../../../components/repos/app-template
resources:
  - ./helmrelease.yaml
configMapGenerator:
  - files:
      - nut.conf=./resources/nut.conf
      - ups.conf=./resources/ups.conf
      - upsd.conf=./resources/upsd.conf
      - upsd.users=./resources/upsd.users
      - upsmon.conf=./resources/upsmon.conf
    name: network-ups-tools-config
generatorOptions:
  disableNameSuffixHash: true
