---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: node-problem-detector
spec:
  chartRef:
    kind: OCIRepository
    name: node-problem-detector
  interval: 30m
  values:
    image:
      repository: registry.k8s.io/node-problem-detector/node-problem-detector
      tag: v1.36.0@sha256:b4db5a168c5f6192c3fb3d650920d192d83776598fcdfcc092d16ca8dc9213ff

    metrics:
      serviceMonitor:
        enabled: true
    resources:
      requests:
        cpu: 25m
        memory: 128Mi
      limits:
        memory: 256Mi
