---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./beast-mass-storage-pvc.yaml
  - ./ceph.yaml
  - ./frigate-media-pvc.yaml
  - ./prometheus.yaml
  - ./security-storage-diskspace.yaml
  - ./security-storage-memory.yaml
  - ./spark-memory.yaml
  - ./zot-data-pvc.yaml
