---
authentication:
    api_keys:
      my_api_key:
        key: ${SLSKD_API_KEY}
        cidr: 10.0.0.0/8,192.168.0.0/16
directories:
  downloads: /media/complete
  incomplete: /media/incomplete
flags:
  no_version_check: true
metrics:
  enabled: true
  url: /metrics
  authentication:
    disabled: true
permissions:
  file:
    mode: 750
remote_configuration: false
shares:
  directories:
    - /media/shared
  filters:
    - \.ini$
    - Thumbs.db$
    - \.DS_Store$
