---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/postgresql.cnpg.io/cluster_v1.json
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: postgres-medikeep
spec:
  instances: 3

  imageName: ghcr.io/cloudnative-pg/postgresql:17.5

  primaryUpdateStrategy: unsupervised

  failoverDelay: 30

  replicationSlots:
    highAvailability:
      enabled: true

  postgresql:
    parameters:
      timezone: "America/New_York"
      max_slot_wal_keep_size: 10GB

  storage:
    size: 10Gi
    storageClass: ceph-block

  resources:
    requests:
      cpu: 100m
      memory: 512Mi

  enableSuperuserAccess: true
  superuserSecret:
    name: cloudnative-pg

  monitoring:
    enablePodMonitor: true

  plugins:
    - name: barman-cloud.cloudnative-pg.io
      isWALArchiver: true
      parameters: &params
        barmanObjectName: garage-medikeep
        serverName: postgres-medikeep-backup

  # bootstrap:
  #   recovery:
  #     source: source

  externalClusters:
    - name: source
      plugin:
        name: barman-cloud.cloudnative-pg.io
        parameters: *params
