---
# yaml-language-server: $schema=https://k8s-schemas.bjw-s.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app ha-mcp
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  targetNamespace: mcp-system
  path: "./kubernetes/apps/mcp-system/ha-mcp/app"
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-ops-kubernetes
    namespace: flux-system
  wait: false
  interval: 1h
  retryInterval: 2m
  timeout: 5m
  dependsOn:
    - name: mcp-gateway
      namespace: mcp-system

---
# yaml-language-server: $schema=https://k8s-schemas.bjw-s.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app ha-mcp-mcpserverregistration
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  targetNamespace: mcp-system
  path: "./kubernetes/apps/mcp-system/ha-mcp/mcp"
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-ops-kubernetes
    namespace: flux-system
  wait: false
  interval: 1h
  retryInterval: 2m
  timeout: 5m
  dependsOn:
    - name: ha-mcp
      namespace: mcp-system
    - name: mcp-gateway
      namespace: mcp-system
