---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/kustomization-kustomize-v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: romm
spec:
  targetNamespace: media
  path: "./kubernetes/apps/media/romm/app"
  interval: 1h
  timeout: 5m
  prune: true
  wait: false
  sourceRef:
    kind: GitRepository
    name: home-ops-kubernetes
    namespace: flux-system
  dependsOn:
    - name: romm
      namespace: databases
    - name: dragonfly-cluster
      namespace: databases
    - name: rook-ceph-cluster
      namespace: rook-ceph
