---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app slskd
spec:
  chartRef:
    kind: OCIRepository
    name: app-template
  interval: 30m

  values:
    defaultPodOptions:
      securityContext:
        fsGroup: 568
        fsGroupChangePolicy: OnRootMismatch
        runAsGroup: 568
        runAsNonRoot: true
        runAsUser: 568
        seccompProfile: {type: RuntimeDefault}

    controllers:
      slskd:
        annotations:
          reloader.stakater.com/auto: "true"
        type: statefulset
        containers:
          app:
            image:
              repository: ghcr.io/slskd/slskd
              tag: 0.25.0@sha256:6a91991c05b7cbbe4e3dcc1f5e10f88d00a68f7ad2ef8a820b79496441b9b78c

            env:
              DOTNET_BUNDLE_EXTRACT_BASE_DIR: /tmp/.net
              SLSKD_APP_DIR: /config
              SLSKD_HTTP_PORT: &httpPort 5030
              SLSKD_NO_AUTH: true
              SLSKD_NO_HTTPS: true
              SLSKD_NO_VERSION_CHECK: true
              SLSKD_SLSK_LISTEN_PORT: &soulseekPort 50300

            envFrom:
              - secretRef:
                  name: *app

            probes:
              liveness: &probes
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /health
                    port: *httpPort
                  failureThreshold: 3
                  initialDelaySeconds: 0
                  periodSeconds: 10
                  timeoutSeconds: 1
              readiness: *probes

            resources:
              requests:
                cpu: 25m
                memory: 1G
              limits:
                memory: 1G

            securityContext:
              allowPrivilegeEscalation: false
              capabilities: {drop: ["ALL"]}
              readOnlyRootFilesystem: true

    service:
      app:
        ports:
          http:
            port: *httpPort
    route:
      main:
        annotations:
          glance/name: "Soulseek"
          glance/show: "true"
          glance/icon: "https://cdn.jsdelivr.net/gh/homarr-labs/dashboard-icons/png/soulseek.png"
          glance/id: "Downloads"
        hostnames:
          - "soulseek.${SECRET_DOMAIN}"
        parentRefs:
          - name: internal
            namespace: network
            sectionName: https
        rules:
          - backendRefs:
              - identifier: app
                port: *httpPort

    persistence:
      config:
        existingClaim: slskd-config-pvc

      config-file:
        type: configMap
        name: slskd-configmap
        globalMounts:
          - path: /config/slskd.yml
            subPath: slskd.yml
            readOnly: true

      media:
        existingClaim: slskd-downloads-pvc

      tmp:
        type: emptyDir


    serviceMonitor:
      app:
        endpoints:
          - port: http
            scheme: http
            path: /metrics
            interval: 1m
            scrapeTimeout: 10s
        serviceName: slskd
