---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app music-assistant
spec:
  chartRef:
    kind: OCIRepository
    name: app-template

  interval: 30m
  values:
    controllers:
      main:
        pod:
          securityContext:
            fsGroup: 1001
            fsGroupChangePolicy: "OnRootMismatch"
            runAsGroup: 1001
            runAsNonRoot: true
            runAsUser: 1000

        annotations:
          reloader.stakater.com/auto: "true"

        type: statefulset
        containers:
          main:
            image:
              repository: ghcr.io/music-assistant/server
              tag: 2.9.0b8

            resources:
              requests:
                cpu: 15m
                memory: 1.4Gi
              limits:
                memory: 1.4Gi

    service:
      main:
        type: LoadBalancer
        annotations:
          lbipam.cilium.io/ips: ${SVC_MUSIC_ASSISTANT_ADDR}
        controller: main
        externalTrafficPolicy: Cluster
        ports:
          http:
            port: &httpPort 8095
          http2:
            port: 1780
          snapserver:
            port: 1704

    route:
      main:
        annotations:
          startpunkt.ullberg.us/enable: "true"
          startpunkt.ullberg.us/name: "Music Assistant"
          startpunkt.ullberg.us/icon: "mdi:headphones"
          startpunkt.ullberg.us/group: "media"
          startpunkt.ullberg.us/instance: "user"
          glance/name: "Music Assistant"
          glance/show: "true"
          glance/icon: "https://cdn.jsdelivr.net/gh/homarr-labs/dashboard-icons/png/music-assistant.png"
          glance/id: "Media"

        hostnames:
          - "{{ .Release.Name }}.${SECRET_DOMAIN}"
        parentRefs:
          - name: internal
            namespace: network
            sectionName: https
        rules:
          - backendRefs:
              - identifier: main
                port: *httpPort
    persistence:
      data:
        existingClaim: music-assistant-data-pvc

      media:
        existingClaim: music-assistant-music-pvc

      tmpfs:
        type: emptyDir
        globalMounts:
          - path: /.audio
            subPath: .audio
