---
# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/master-standalone-strict/configmap-v1.json
apiVersion: v1
kind: ConfigMap
metadata:
  name: romm-config
data:
  config.yml: |
    exclude:
      platforms: []
      roms:
        single_file:
          names: []
          extensions: []
        multi_file:
          names: []
          parts:
            names: []
            extensions: []
    filesystem:
      roms_folder: roms
    system:
      platforms: {}
