---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: romm
spec:
  refreshInterval: 15m
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: romm-secret
    template:
      engineVersion: v2
      data:
        # App
        ROMM_AUTH_SECRET_KEY: "{{ .ROMM_AUTH_SECRET_KEY }}"

        # OIDC (Authelia)
        OIDC_CLIENT_SECRET: "{{ .ROMM_OIDC_CLIENT_SECRET }}"

        # Database
        DB_HOST: postgres-romm-rw.databases.svc.cluster.local
        DB_PORT: "5432"
        DB_NAME: romm
        DB_USER: "{{ .POSTGRES_USER }}"
        DB_PASSWD: "{{ .POSTGRES_PASS }}"

        # Postgres init
        INIT_POSTGRES_DBNAME: romm
        INIT_POSTGRES_HOST: postgres-romm-rw.databases.svc.cluster.local
        INIT_POSTGRES_USER: "{{ .POSTGRES_USER }}"
        INIT_POSTGRES_PASS: "{{ .POSTGRES_PASS }}"
        INIT_POSTGRES_SUPER_PASS: "{{ .POSTGRES_SUPER_PASS }}"
  dataFrom:
    - extract:
        key: cloudnative-pg
    - extract:
        key: romm
