---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./cnp-allow.yaml
  - ./cronjob-memory-sync.yaml
  - ./externalsecret.yaml
  - ./rbac.yaml
configMapGenerator:
  - name: memory-sync-ingest
    files:
      - ingest.py=./resources/ingest.py
generatorOptions:
  disableNameSuffixHash: true
