---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
components:
  - ../../../../components/repos/app-template
configMapGenerator:
  - name: memory-mcp-schema
    files:
      - schema.sql=./resources/schema.sql
generatorOptions:
  disableNameSuffixHash: true
resources:
  - ./cnp-allow.yaml
  - ./helmrelease.yaml
  - ./schema-init-job.yaml
