#!/bin/sh
#
# Clear the /tmp directory.
#
# LOVENET OVERRIDE of jlesage/docker-baseimage's 08-clear-tmp-dir.sh.
# Baseimage 4.12.x symlinks /run -> /tmp/run and then runs `rm -rf /tmp/run`
# here. Under CRI-O we mount an emptyDir at /run (so the runtime can create
# /run/.containerenv at all), which makes /tmp/run an active mount point.
# `rm -rf /tmp/run` then fails with EBUSY and, because of `set -e`, aborts
# init -> the app container never starts. See jlesage/docker-baseimage#18.
# Fix: clear only the CONTENTS of /tmp/run and skip active mount points,
# never trying to remove the /tmp/run mount itself.
#

set -e # Exit immediately if a command exits with a non-zero status.
set -u # Treat unset variables as an error.

# Clear /tmp/run, but leave the mount point itself and any active mounts
# inside it (e.g. the runtime-injected /run/.containerenv) in place.
if [ -d /tmp/run ]; then
    find /tmp/run -mindepth 1 -maxdepth 1 | while IFS= read -r entry; do
        mountpoint -q "$entry" && continue
        rm -rf "$entry"
    done
fi

# Remove everything under /tmp, except:
#   - /tmp/.cont-env-internal: generated by the init script.
#   - /tmp/run: handled above.
find /tmp -mindepth 1 -maxdepth 1 ! -name '.cont-env-internal' ! -name 'run' -exec rm -rf {} +

# vim:ft=sh:ts=4:sw=4:et:sts=4
