---
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: "Renovate"

on:
  workflow_dispatch:
    inputs:
      dryRun:
        description: Dry Run
        default: "false"
        required: false
      logLevel:
        description: Log Level
        default: debug
        required: false
      version:
        description: Renovate version
        default: latest
        required: false
  schedule:
    - cron: "0 * * * *" # Every hour
  push:
    branches: ["main"]
    paths:
      - .github/renovate.json5
      - .github/renovate/**.json5

concurrency:
  group: ${{ github.workflow }}-${{ github.event.number || github.ref }}
  cancel-in-progress: true

env:
  LOG_LEVEL: "${{ inputs.logLevel || 'debug' }}"
  RENOVATE_AUTODISCOVER: true
  RENOVATE_AUTODISCOVER_FILTER: "${{ github.repository }}"
  RENOVATE_DRY_RUN: "${{ inputs.dryRun == true }}"
  RENOVATE_PLATFORM: github
  RENOVATE_PLATFORM_COMMIT: true
  WORKFLOW_RENOVATE_VERSION: "${{ inputs.version || 'latest' }}"

jobs:
  renovate:
    name: Renovate
    runs-on: ubuntu-latest
    steps:
      - name: Generate Token
        uses: actions/create-github-app-token@1b10c78c7865c340bc4f6099eb2f838309f1e8c3 # v3
        id: app-token
        with:
          app-id: "${{ secrets.LOVENET_RENOVATE_OPERATOR_APP_ID }}"
          private-key: "${{ secrets.LOVENET_RENOVATE_OPERATOR_PRIVATE_KEY }}"

      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          token: "${{ steps.app-token.outputs.token }}"

      - name: Renovate
        uses: renovatebot/github-action@83ec54fee49ab67d9cd201084c1ff325b4b462e4 # v46.1.10
        with:
          configurationFile: .github/renovate.json5
          token: "${{ steps.app-token.outputs.token }}"
          renovate-version: "${{ env.WORKFLOW_RENOVATE_VERSION }}"
