---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app comfyui
spec:
  chartRef:
    kind: OCIRepository
    name: app-template
  interval: 30m
  values:
    controllers:
      comfyui:
        pod:
          affinity:
            nodeAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
                nodeSelectorTerms:
                  - matchExpressions:
                      - key: nvidia.com/gpu.present
                        operator: In
                        values:
                          - "true"

          nodeSelector:
            nvidia.com/gpu.present: "true"

          priorityClassName: ai-gpu-critical

          runtimeClassName: nvidia

        annotations:
          reloader.stakater.com/auto: "true"

        type: statefulset

        containers:
          app:
            image:
              repository: ghcr.io/ai-dock/comfyui
              tag: v2-cuda-12.1.1-base-22.04-v0.2.7@sha256:ca4c95d4d4743d7d5683e57f5e0358fe586bc57578f66c2a844e9fa0650cc619

            env:
              AUTO_UPDATE: "false"
              CF_QUICK_TUNNELS: "false"
              DIRECT_ADDRESS_GET_WAN: "true"
              PROVISIONING_SCRIPT: "https://raw.githubusercontent.com/ai-dock/comfyui/main/config/provisioning/flux.sh"
              SERVERLESS: "false"
              SERVICEPORTAL_URL: "comfyui.${SECRET_DOMAIN}"
              WEB_ENABLE_AUTH: "false"
              WORKSPACE: "/workspace"

            resources:
              requests:
                nvidia.com/gpu: 1 # requesting 1 GPU
                cpu: 500m
                memory: 10Gi
              limits:
                memory: 32Gi
                nvidia.com/gpu: 1 # requesting 1 GPU

            securityContext:
              privileged: true

    service:
      app:
        controller: comfyui
        ports:
          http:
            port: &httpPort 8188

    route:
      main:
        annotations:
          glance/name: "Comfy UI"
          glance/show: "true"
          glance/icon: "https://cdn.jsdelivr.net/gh/homarr-labs/dashboard-icons/png/comfy-ui.png"
          glance/id: "AI"
        hostnames:
          - "{{ .Release.Name }}.${SECRET_DOMAIN}"
        parentRefs:
          - name: internal
            namespace: network
            sectionName: https
        rules:
          - backendRefs:
              - identifier: app
                port: *httpPort

    persistence:
      config:
        type: configMap
        name: comfyui-configmap
        advancedMounts:
          comfyui:
            app:
              - path: /workspace/ComfyUI/custom_nodes/ComfyUI-Manager/config.ini
                subPath: config.ini
                readOnly: true
      output:
        enabled: true
        existingClaim: comfyui-output-pvc
        globalMounts:
          - path: /workspace/ComfyUI/output

      workspace:
        enabled: true
        existingClaim: comfyui-workspace-pvc
        globalMounts:
          - path: /workspace
